function plotsignals0bis100(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 17-Nov-2019 18:24:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(YMatrix1);

% preserve the X-limits of the axes
xlim(axes1,[0 100]);
box(axes1,'on');
